#Requires -Version 7
<#
Regenerates assets/opam-lock/opam_file_format.ml: a single-file amalgam of
opam-file-format (https://github.com/ocaml/opam-file-format) used by
assets/opam-lock/dk_opam_lock.ml to parse opam syntax at Dk.OpamLock.Solve time.

Run only when bumping the pinned upstream version (rare; the opam file format
is stable). Requires an opam switch whose bin has ocamllex and menhir
(`opam install menhir`); DkML's ocamlyacc cannot process opamBaseParser.mly
(menhir-only grammar: positional refs to valueless terminals).

After regenerating: update the OpamFileFormat asset byteSize/sha256 in dk.u
(hash the checked-in LF bytes: git show :assets/opam-lock/opam_file_format.ml).
#>
param(
  # Upstream release tag.
  [string]$Version = '2.2.0',
  # SHA-256 of the release tarball for that tag.
  [string]$TarballSha256 = '2f44edc6fac952942a7963d45c5837bfc5c933fe9f5cb62d0c05ee4a9187e0e4',
  # opam switch providing ocamllex + menhir; empty = the current switch.
  [string]$OpamSwitch = ''
)
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $repoRoot 'assets\opam-lock\opam_file_format.ml'

$opamArgs = @('exec')
if ($OpamSwitch -ne '') { $opamArgs += "--switch=$OpamSwitch" }
$opamArgs += '--'
function Invoke-Tool {
  param([Parameter(Mandatory)][string[]]$Argv)
  & opam @opamArgs @Argv
  if ($LASTEXITCODE -ne 0) { throw "command failed ($LASTEXITCODE): $($Argv -join ' ')" }
}

& opam @opamArgs menhir --version *> $null
if ($LASTEXITCODE -ne 0) {
  throw "menhir not found in the opam switch. Run: opam install menhir  (or pass -OpamSwitch)"
}
$menhirVersion = (& opam @opamArgs menhir --version | Select-Object -First 1).Trim()
$ocamlVersion = (& opam @opamArgs ocaml -vnum | Select-Object -First 1).Trim()

$work = Join-Path ([IO.Path]::GetTempPath()) "opam-file-format-amalgam-$([guid]::NewGuid().ToString('n').Substring(0, 8))"
New-Item -ItemType Directory $work | Out-Null
try {
  $tgz = Join-Path $work "opam-file-format-$Version.tar.gz"
  curl.exe -fsSLo $tgz "https://github.com/ocaml/opam-file-format/archive/refs/tags/$Version.tar.gz"
  if ($LASTEXITCODE -ne 0) { throw "download failed" }
  $actual = (Get-FileHash $tgz -Algorithm SHA256).Hash.ToLower()
  if ($actual -ne $TarballSha256.ToLower()) {
    throw "tarball sha256 mismatch: expected $TarballSha256, got $actual"
  }
  tar -xzf $tgz -C $work
  if ($LASTEXITCODE -ne 0) { throw "extract failed" }
  $src = Join-Path $work "opam-file-format-$Version\src"

  Push-Location $src
  try {
    Invoke-Tool @('ocamllex', '-q', 'opamLexer.mll')
    Invoke-Tool @('menhir', 'opamBaseParser.mly')
  } finally {
    Pop-Location
  }

  # Concatenation order follows the module dependency chain. Domain is the
  # compat shim for OCaml < 5.0 (DkML is 4.14.x): OpamLexer uses Domain.DLS.
  $parts = [ordered]@{
    'Domain'          = Join-Path $src 'compat\domain.ml'
    'OpamParserTypes' = Join-Path $src 'opamParserTypes.ml'
    'OpamBaseParser'  = Join-Path $src 'opamBaseParser.ml'
    'OpamLexer'       = Join-Path $src 'opamLexer.ml'
    'OpamParser'      = Join-Path $src 'opamParser.ml'
    'OpamPrinter'     = Join-Path $src 'opamPrinter.ml'
  }
  $header = @"
(* Generated by tools/update-opam-file-format.ps1 -- DO NOT EDIT.

   Single-file amalgam of opam-file-format $Version
   (https://github.com/ocaml/opam-file-format, tag $Version,
   tarball sha256 $TarballSha256).
   Generated with ocamllex/menhir from OCaml $ocamlVersion, $menhirVersion.

   License: GNU Lesser General Public License version 2.1, with the special
   exception on linking described in the upstream LICENSE file.
   Copyright 2012-2020 OCamlPro; Copyright 2012 INRIA. Each embedded module
   retains its original copyright header below.

   Consumers compile this file as its own unit and ``open Opam_file_format``
   to reach OpamParserTypes/OpamParser/OpamPrinter (e.g. dk_opam_lock.ml). *)


"@
  $header = $header -replace "`r`n", "`n"
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.Append($header)
  foreach ($name in $parts.Keys) {
    $body = [System.IO.File]::ReadAllText($parts[$name]) -replace "`r`n", "`n"
    [void]$sb.Append("module $name = struct`n")
    [void]$sb.Append($body)
    if (-not $body.EndsWith("`n")) { [void]$sb.Append("`n") }
    [void]$sb.Append("end`n`n")
  }
  New-Item -ItemType Directory (Split-Path -Parent $outFile) -Force | Out-Null
  [System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

  $bytes = (Get-Item $outFile).Length
  $sha = (Get-FileHash $outFile -Algorithm SHA256).Hash.ToLower()
  Write-Host "wrote $outFile"
  Write-Host "  bytes: $bytes"
  Write-Host "  sha256: $sha  (dk.u OpamFileFormat asset; re-hash via git show after commit)"
} finally {
  Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
}
